require("endoxide.options")
require("endoxide.keymaps")
require("endoxide.augroup")
require("endoxide.lazy")
require("endoxide.cmp")
-- require("endoxide.nvim-tree")
require("endoxide.treesitter")
require("endoxide.comment")
require("endoxide.lsp")
require("endoxide.dap-setup")
require("endoxide.latex")
require("endoxide.snippets")
require("endoxide.sessions")
require("endoxide.lualine-setup")
require("endoxide.colors")
