require("endoxide.globals")
require("endoxide.options")
require("endoxide.keymaps")
require("endoxide.autocommand").setup()
require("endoxide.macros")
-- require("endoxide.colors")
require("endoxide.lazy")
require("endoxide.lsp")
require("endoxide.dap-setup")
require("endoxide.user_commands")
